### ISSUE TITLE
Binary installer for windows doesn't install required DLLS

### ISSUE THREAD

**Issue by MattCosturos** [mtconnect/dataminer#2]
libgcc_s_seh-1.dll  and libstdc++-6.dll are not installed when using the windows binary  installer.

**Comment by simonyg** [comment]
Unfortunately, it does have some MingGW dll dependencies:

 ldd dataminer.exe
        ntdll.dll => /cygdrive/c/Windows/SYSTEM32/ntdll.dll (0x7ffbc9ac0000)
        KERNEL32.DLL => /cygdrive/c/Windows/System32/KERNEL32.DLL (0x7ffbc9160000)
        KERNELBASE.dll => /cygdrive/c/Windows/System32/KERNELBASE.dll (0x7ffbc6ab0000)
        ADVAPI32.dll => /cygdrive/c/Windows/System32/ADVAPI32.dll (0x7ffbc93c0000)
        msvcrt.dll => /cygdrive/c/Windows/System32/msvcrt.dll (0x7ffbc9320000)
        sechost.dll => /cygdrive/c/Windows/System32/sechost.dll (0x7ffbc75f0000)
        RPCRT4.dll => /cygdrive/c/Windows/System32/RPCRT4.dll (0x7ffbc74c0000)
        GDI32.dll => /cygdrive/c/Windows/System32/GDI32.dll (0x7ffbc92d0000)
        gdi32full.dll => /cygdrive/c/Windows/System32/gdi32full.dll (0x7ffbc6e70000)
        msvcp_win.dll => /cygdrive/c/Windows/System32/msvcp_win.dll (0x7ffbc6a10000)
        ucrtbase.dll => /cygdrive/c/Windows/System32/ucrtbase.dll (0x7ffbc6d00000)
        USER32.dll => /cygdrive/c/Windows/System32/USER32.dll (0x7ffbc9010000)
        win32u.dll => /cygdrive/c/Windows/System32/win32u.dll (0x7ffbc7000000)
        WS2_32.dll => /cygdrive/c/Windows/System32/WS2_32.dll (0x7ffbc9600000)
        **libgcc_s_seh-1.dll => /cygdrive/c/mingw-w64/x86_64-7.3.0-posix-seh-rt_v5-rev0/mingw64/bin/libgcc_s_seh-1.dll (0x61440000)
        libwinpthread-1.dll => /cygdrive/c/mingw-w64/x86_64-7.3.0-posix-seh-rt_v5-rev0/mingw64/bin/libwinpthread-1.dll (0x64940000)
        libstdc++-6.dll => /cygdrive/c/mingw-w64/x86_64-7.3.0-posix-seh-rt_v5-rev0/mingw64/bin/libstdc++-6.dll (0x6fc40000)**

Work around is to install MinGW first.

**Comment by simonyg** [comment]
Make v1.1.1 to fix the build without MinGW dependencies.

Windows: [dataminer-1.1.1-win64.zip](https://github.com/mtconnect/dataminer/files/4228900/dataminer-1.1.1-win64.zip)
